-- Seed: Service catalog is loaded via migration 002_services_catalog.sql (96 partner-fulfilled services)

-- Default Account Manager
INSERT INTO account_managers (name, telegram_id, telegram_link, support_hours) VALUES
('Abhay', '@Abhay_TWL', 'https://t.me/Abhay_TWL', 'Monday - Saturday, 9AM - 6PM UTC');

-- Legal Pages
INSERT INTO legal_pages (slug, title, content) VALUES
('terms', 'Terms & Conditions', 'TokenWeb3Listing.com Terms & Conditions. Last Updated: June 2026. By accessing TokenWeb3Listing.com, creating an account, submitting information, purchasing services, or using our platform, you agree to comply with these Terms & Conditions. Services are provided on a best-effort basis. We do not guarantee exchange listing approval, CoinMarketCap approval, CoinGecko approval, wallet listing approval, media publication approval, trending rankings, trading volume, fundraising success, or token price appreciation. Full payment is required before work begins. Payments are non-refundable except where specifically covered by the Refund Policy.'),
('privacy', 'Privacy Policy', 'TokenWeb3Listing.com Privacy Policy. Last Updated: June 2026. We collect personal information, business information, blockchain information, and technical information. We do not sell personal data. Information may be shared with service providers only as necessary for service delivery. We implement SSL encryption, access controls, role-based permissions, and secure storage.'),
('refund', 'Refund Policy', 'TokenWeb3Listing.com Refund Policy. Last Updated: June 2026. Refunds may be approved when payment is duplicated, service cannot be delivered, service has not started within agreed timeline, or order is cancelled by TokenWeb3Listing.com. Refunds will NOT be provided when third-party platforms reject applications, clients provide incorrect information, or work has already started or completed. Approved refunds processed within 7-14 business days.'),
('aml-kyc', 'AML & KYC Policy', 'TokenWeb3Listing.com AML & KYC Policy. Last Updated: June 2026. We are committed to preventing money laundering, terrorist financing, fraud, and sanctions violations. We reserve the right to request individual verification, business verification, and enhanced due diligence. We do not support projects related to terrorism financing, sanctioned entities, fraud schemes, or illegal securities offerings.'),
('sla', 'Service Level Agreement', 'TokenWeb3Listing.com SLA. Last Updated: June 2026. Standard support response within 24 hours. Priority support within 12 hours. Enterprise support within 4 hours. Standard services expected delivery 24-72 hours. Enterprise services timeline custom based on scope.'),
('agent-policy', 'Agent & Affiliate Policy', 'TokenWeb3Listing.com Agent & Affiliate Policy. Agents may earn commissions ranging from 10% to 30% depending on service category. Minimum withdrawal: $100 USD. Supported methods: USDT, Bank Transfer. Agents operate as independent contractors.'),
('disclaimer', 'Legal Disclaimer', 'TokenWeb3Listing.com is an independent Web3 consulting and service marketplace. We are not affiliated with or endorsed by any exchange, wallet provider, media company, audit provider, or third-party platform unless explicitly stated. All trademarks belong to their respective owners. Service outcomes remain subject to third-party review and policies.');

-- Sample Blog Posts
INSERT INTO blog_posts (title, slug, excerpt, content, is_published, published_at) VALUES
('How to Prepare for CoinMarketCap Listing', 'coinmarketcap-listing-guide', 'Essential steps to prepare your token project for CoinMarketCap application.', 'CoinMarketCap listing requires proper documentation, verified contract, active community, and accurate project data. This guide covers the complete preparation process including website requirements, social media verification, and application best practices.', true, NOW()),
('BSCScan Token Update Guide', 'bscscan-update-guide', 'Step-by-step guide for updating your token information on BSCScan.', 'Learn how to update your token logo, social links, and contract verification on BSCScan. Our team can handle the entire process within 24-48 hours.', true, NOW()),
('Web3 Agent Program: Earn Commissions', 'agent-program-guide', 'Join our agent program and earn 10-30% commission on every referral.', 'The TokenWeb3Listing Agent Program allows marketing agencies, influencers, and consultants to earn recurring commissions by referring Web3 projects to our platform.', true, NOW());
