-- Replace entire catalog with 9 core admin services (removes Binance Ecosystem Support).

DELETE FROM commission_ledger WHERE order_id IS NOT NULL;
DELETE FROM orders;
DELETE FROM services;

INSERT INTO services (
  category_id,
  name,
  slug,
  description,
  overview,
  pricing_model,
  price,
  service_fee,
  commission_type,
  commission_value,
  estimated_tat,
  payment_terms,
  requires_third_party_ack,
  third_party_fee_note,
  badge,
  logo_url,
  whats_included,
  supported_platforms,
  process_steps,
  listing_type,
  networks,
  refund_policy,
  required_documents,
  faqs,
  terms_conditions,
  proof_of_work,
  sort_order,
  is_active
)
SELECT
  c.id,
  v.name,
  v.slug,
  v.description,
  v.overview,
  v.pricing_model::pricing_model,
  v.price,
  v.service_fee,
  v.commission_type::commission_type,
  v.commission_value,
  v.estimated_tat,
  v.payment_terms,
  v.requires_third_party_ack,
  v.third_party_fee_note,
  v.badge,
  v.logo_url,
  v.whats_included::jsonb,
  v.supported_platforms::jsonb,
  v.process_steps::jsonb,
  v.listing_type,
  v.networks,
  v.refund_policy,
  v.required_documents,
  v.faqs::jsonb,
  v.terms_conditions,
  v.proof_of_work,
  v.sort_order,
  true
FROM (
  VALUES
  (
    'listing-services',
    'CEX Exchange Listing Services',
    'cex-exchange-listing-services',
    'End-to-end centralized exchange listing support for Web3 tokens — application prep, compliance review, and partner follow-up across top CEX platforms.',
    'Our CEX Exchange Listing Services help crypto projects navigate the complex world of centralized exchange listings. From documentation and legal readiness to direct submission and follow-up with exchange listing teams, we manage the full pipeline so your token can reach millions of traders on major exchanges.',
    'quote',
    NULL::decimal,
    299::decimal,
    'percentage',
    15::decimal,
    '14–30 Days',
    '100% Advance',
    true,
    'Exchange listing fees charged by CEX partners are separate and vary by platform.',
    'popular',
    NULL,
    '["Exchange application preparation","Compliance & documentation review","Direct submission to CEX partners","Listing follow-up & status tracking","Post-listing visibility support","Dedicated account manager"]',
    '["Binance","Bitget","MEXC","Gate.io","KuCoin","Bybit","OKX","HTX"]',
    '[{"title":"Project Assessment","description":"We evaluate your tokenomics, legal standing, and exchange readiness."},{"title":"Documentation","description":"Prepare exchange-specific application packs and compliance materials."},{"title":"Submission","description":"Submit to selected CEX partners with professional presentation."},{"title":"Follow-up","description":"Active communication with exchange listing teams until decision."},{"title":"Listing Launch","description":"Coordinate announcement and post-listing marketing support."}]',
    'CEX Listing',
    'Multi-chain',
    'Non-Refundable after work begins',
    ARRAY['Token contract address','Project whitepaper / litepaper','Logo (512x512 PNG)','Team KYC documents','Legal opinion (if required)','Tokenomics breakdown','Website & social links'],
    '[{"question":"Which exchanges can you list on?","answer":"We support applications to major CEX platforms including Binance ecosystem partners, Bitget, MEXC, Gate, KuCoin, and more. Final approval is at each exchange''s discretion."},{"question":"Do you guarantee listing approval?","answer":"No. Exchanges make independent decisions. We maximize approval chances through professional preparation and follow-up."},{"question":"How long does CEX listing take?","answer":"Typically 14–30 days depending on exchange queue, project readiness, and compliance review timelines."}]',
    'CEX listing outcomes depend on third-party exchange policies. TokenWeb3Listing provides preparation and submission services on a best-effort basis. Payment is 100% advance and non-refundable once work begins.',
    'Supported 80+ token listings across Tier-1 and Tier-2 centralized exchanges with an average 72% application acceptance rate on prepared submissions.',
    1
  ),
  (
    'wallet-listing',
    'Web3 Wallet Listing Services',
    'web3-wallet-listing-services',
    'Get your token integrated into leading Web3 wallets — Trust Wallet, MetaMask asset lists, and multi-chain wallet ecosystems for maximum holder accessibility.',
    'Web3 Wallet Listing Services ensure your token appears in the wallets your community actually uses. We handle asset metadata submission, chain integration requests, and follow-up with wallet provider review teams across EVM and non-EVM networks.',
    'enterprise',
    NULL::decimal,
    149::decimal,
    'percentage',
    15::decimal,
    '7–14 Days',
    '100% Advance',
    true,
    'Some wallet providers charge separate review or integration fees.',
    'new',
    NULL,
    '["Wallet asset metadata submission","Multi-chain wallet integration","Logo & token info optimization","Wallet provider follow-up","Community visibility boost","Integration confirmation report"]',
    '["Trust Wallet","MetaMask","Coinbase Wallet","TokenPocket","SafePal","Ledger Live"]',
    '[{"title":"Asset Audit","description":"Verify contract, decimals, and chain compatibility for wallet standards."},{"title":"Metadata Prep","description":"Format logo, symbol, and project info per wallet provider specs."},{"title":"Submission","description":"Submit listing requests to selected wallet ecosystems."},{"title":"Review Follow-up","description":"Track application status and respond to provider feedback."},{"title":"Go Live","description":"Confirm token visibility in target wallets."}]',
    'Wallet Integration',
    'ETH, BSC, Polygon, Arbitrum, Base',
    'Non-Refundable after submission',
    ARRAY['Verified contract address','Token logo (PNG/SVG)','Official website URL','CoinGecko or CMC link (if available)','Project description (max 500 chars)'],
    '[{"question":"Which wallets do you support?","answer":"Trust Wallet, MetaMask token lists, Coinbase Wallet, TokenPocket, SafePal, and more upon request."},{"question":"Is contract verification required?","answer":"Yes. Most wallet providers require a verified smart contract on a supported blockchain explorer."}]',
    'Wallet listing approval is controlled by third-party wallet providers. We provide professional submission and follow-up services. Payment is 100% advance.',
    'Integrated 200+ tokens into major Web3 wallet ecosystems across 12 blockchain networks.',
    2
  ),
  (
    'market-making',
    'Market Making (MM) Bot Services',
    'market-making-mm-bot-services',
    'Professional market making bot deployment for CEX and DEX pairs — liquidity depth, spread management, and 24/7 automated order book support.',
    'Market Making (MM) Bot Services give your token healthy trading activity and tight spreads on exchanges. Our team configures institutional-grade MM bots tailored to your pair, volume targets, and risk parameters on both centralized and decentralized venues.',
    'quote',
    NULL::decimal,
    NULL::decimal,
    'percentage',
    12::decimal,
    '3–7 Days setup',
    '100% Advance',
    false,
    NULL,
    'hot',
    NULL,
    '["MM bot strategy design","CEX & DEX pair configuration","24/7 automated liquidity","Spread & depth optimization","Daily performance reporting","Risk management controls"]',
    '["PancakeSwap","Uniswap","MEXC","Gate.io","KuCoin","Bybit"]',
    '[{"title":"Strategy Call","description":"Define volume targets, spread requirements, and exchange pairs."},{"title":"Bot Configuration","description":"Deploy and calibrate MM bot with your API keys securely."},{"title":"Live Monitoring","description":"24/7 bot operation with real-time order book management."},{"title":"Reporting","description":"Daily performance dashboards and liquidity metrics."},{"title":"Optimization","description":"Ongoing tuning based on market conditions."}]',
    'MM Bot Deployment',
    'BSC, ETH, SOL',
    'Partial refund before bot deployment only',
    ARRAY['Exchange API keys (read/trade)','Target trading pairs','Daily volume targets','Risk tolerance parameters','LP wallet access (for DEX MM)'],
    '[{"question":"Do you need my exchange API keys?","answer":"Yes, trade-enabled API keys are required for CEX MM. We use secure, encrypted storage and never withdraw funds."},{"question":"Can MM bots run on DEX?","answer":"Yes. We support PancakeSwap, Uniswap, and other AMM pairs with wallet-based MM strategies."}]',
    'Market making involves financial risk. Past performance does not guarantee future results. Client maintains custody of funds. Service fees are non-refundable after bot deployment.',
    'Deployed MM infrastructure for 50+ token pairs maintaining consistent top-10 depth on target exchanges.',
    3
  ),
  (
    'listing-services',
    'Top DEX Exchange Listing Services',
    'top-dex-exchange-listing-services',
    'Launch and list your token on top decentralized exchanges — PancakeSwap, Uniswap, Raydium, and more with liquidity pair setup and visibility boost.',
    'Top DEX Exchange Listing Services cover everything needed to go live on leading decentralized exchanges. From liquidity pool creation and pair configuration to DEX tracker submissions and trending visibility, we make your token tradable and discoverable on DEX platforms.',
    'quote',
    NULL::decimal,
    199::decimal,
    'percentage',
    15::decimal,
    '3–5 Days',
    '100% Advance',
    false,
    NULL,
    NULL,
    NULL,
    '["DEX pair creation & LP setup","Liquidity pool configuration","DEX tracker submissions (DEXScreener, DEXTools)","Trending & visibility campaigns","Anti-bot & sniper protection advice","Launch coordination support"]',
    '["PancakeSwap","Uniswap","Raydium","Jupiter","SushiSwap","Aerodrome"]',
    '[{"title":"Launch Planning","description":"Define chain, pair token, and initial liquidity strategy."},{"title":"Pool Creation","description":"Create and configure liquidity pool on target DEX."},{"title":"Tracker Submission","description":"Submit to DEXScreener, DEXTools, and GeckoTerminal."},{"title":"Visibility Boost","description":"Activate trending and community announcement support."},{"title":"Go-Live","description":"Confirm trading live with proof links."}]',
    'DEX Listing',
    'BSC, ETH, Solana, Base',
    'Non-Refundable after LP deployment',
    ARRAY['Token contract address','Liquidity funds (BNB/ETH/SOL)','Token logo','Project website','Telegram & Twitter links'],
    '[{"question":"Which DEX platforms do you support?","answer":"PancakeSwap, Uniswap V2/V3, Raydium, Jupiter, SushiSwap, Aerodrome, and more."},{"question":"Do I need to provide liquidity?","answer":"Yes. Client provides liquidity funds. We handle pool creation and configuration."}]',
    'DEX listing and liquidity deployment are irreversible on-chain actions. Client retains custody of funds. Service fee is non-refundable after pool creation.',
    'Launched 300+ tokens on top DEX platforms with combined $50M+ initial liquidity deployed.',
    4
  ),
  (
    'trending-services',
    'Top DEX Crypto Website Listing Services',
    'top-dex-crypto-website-listing-services',
    'List your project on top crypto discovery websites and DEX aggregators — CoinSniper, Poocoin, FreshCoins, and premium crypto directory platforms.',
    'Top DEX Crypto Website Listing Services maximize your token''s discoverability across crypto voting sites, launchpads, and DEX aggregator directories. We submit, verify, and promote your project across the platforms traders use to find new tokens daily.',
    'fixed',
    299::decimal,
    NULL::decimal,
    'percentage',
    12::decimal,
    '2–5 Days',
    '100% Advance',
    false,
    NULL,
    'new',
    NULL,
    '["Crypto website & directory submissions","Voting platform listings (CoinSniper, etc.)","DEX aggregator profile setup","Banner & featured placement coordination","SEO-optimized project profile","Multi-platform visibility report"]',
    '["CoinSniper","Poocoin","FreshCoins","CoinHunt","DEXView","CoinDiscovery"]',
    '[{"title":"Profile Build","description":"Create optimized listings with logo, description, and links."},{"title":"Platform Submission","description":"Submit to selected crypto discovery websites."},{"title":"Verification","description":"Complete platform verification steps and KYC if required."},{"title":"Promotion","description":"Coordinate votes, trends, and featured placements."},{"title":"Report","description":"Deliver live links and visibility confirmation."}]',
    'Directory Listing',
    'Multi-chain',
    'Non-Refundable after submission',
    ARRAY['Token contract address','Logo & banner assets','Project description','Website & social links','Liquidity lock proof (if applicable)'],
    '[{"question":"How many platforms are included?","answer":"Our standard package covers 8–12 top crypto discovery websites. Custom packages available on request."}]',
    'Third-party platform policies govern listing approval. We provide submission and promotion services on a best-effort basis.',
    'Listed 500+ projects across top crypto discovery platforms with measurable traffic uplift.',
    5
  ),
  (
    'token-security',
    'Smart Contract Audit Services',
    'smart-contract-audit-services',
    'Professional smart contract security audit — vulnerability assessment, code review, and published audit report for investor and exchange confidence.',
    'Smart Contract Audit Services provide comprehensive security analysis of your token and protocol contracts. Our audit partners identify vulnerabilities, logic flaws, and compliance issues, delivering a published report that builds trust with investors, exchanges, and your community.',
    'fixed',
    1499::decimal,
    NULL::decimal,
    'percentage',
    10::decimal,
    '7–14 Days',
    '50% Advance, 50% on delivery',
    false,
    NULL,
    NULL,
    NULL,
    '["Full smart contract code review","Automated vulnerability scanning","Manual security analysis","Audit report publication","Remediation guidance","Re-audit after fixes (1 round)"]',
    '["Solidity","Rust (Solana)","Move (Aptos/Sui)","Vyper"]',
    '[{"title":"Code Intake","description":"Receive and scope smart contract codebase for audit."},{"title":"Automated Scan","description":"Run industry-standard static analysis tools."},{"title":"Manual Review","description":"Senior auditor performs line-by-line security review."},{"title":"Report Delivery","description":"Published PDF audit report with severity ratings."},{"title":"Remediation","description":"Support one round of fixes and re-verification."}]',
    'Security Audit',
    'EVM, Solana, Aptos',
    'Non-Refundable after audit begins',
    ARRAY['Complete smart contract source code','Deployment addresses','Documentation & whitepaper','Testnet deployment (preferred)'],
    '[{"question":"Which languages do you audit?","answer":"Solidity, Vyper, Rust (Solana/Anchor), Move, and most EVM-compatible languages."},{"question":"Is the audit report public?","answer":"Yes. We provide a publishable audit certificate for your website and CoinGecko/CMC profiles."}]',
    'Audit reports reflect code state at time of review. Client is responsible for post-audit changes. Audit does not guarantee absence of all vulnerabilities.',
    'Completed 150+ smart contract audits with zero critical exploits on audited mainnet deployments.',
    6
  ),
  (
    'listing-services',
    'CoinMarketCap & CoinGecko Listing Services',
    'coinmarketcap-coingecko-listing-services',
    'Get your token listed on CoinMarketCap and CoinGecko — the two most trusted crypto data platforms for price tracking, discovery, and exchange credibility.',
    'CoinMarketCap & CoinGecko Listing Services are essential for any serious crypto project. We manage the complete application process for both platforms — meeting volume, liquidity, and documentation requirements — and follow up until your token is live and trackable by millions of users worldwide.',
    'enterprise',
    NULL::decimal,
    399::decimal,
    'percentage',
    15::decimal,
    '7–21 Days',
    '100% Advance',
    true,
    'CoinMarketCap and CoinGecko may require minimum volume and liquidity thresholds.',
    'popular',
    NULL,
    '["CoinMarketCap application & submission","CoinGecko application & submission","Requirements compliance review","Volume & liquidity guidance","Follow-up with data platform teams","Post-listing profile optimization"]',
    '["CoinMarketCap","CoinGecko","GeckoTerminal"]',
    '[{"title":"Readiness Check","description":"Verify volume, liquidity, and documentation meet platform requirements."},{"title":"Application Prep","description":"Prepare CMC and CG-specific application packages."},{"title":"Submission","description":"Submit applications with optimized project profiles."},{"title":"Follow-up","description":"Active communication with CMC/CG review teams."},{"title":"Live Confirmation","description":"Confirm listing live with profile links delivered."}]',
    'Data Platform Listing',
    'Multi-chain',
    'Non-Refundable after submission',
    ARRAY['Verified contract on supported chain','Active DEX trading pair','Minimum liquidity proof','Website with project info','Social media accounts (Twitter, Telegram)','CoinGecko or CMC competitor link'],
    '[{"question":"What are the minimum requirements?","answer":"Generally: verified contract, active trading on a recognized DEX or CEX, working website, and active social channels. Requirements vary by platform."},{"question":"Can you list on CMC and CG together?","answer":"Yes. Our package covers simultaneous application to both platforms for faster overall visibility."}]',
    'CoinMarketCap and CoinGecko make independent listing decisions. We provide professional application and follow-up services. Third-party platform fees may apply.',
    'Achieved 200+ successful CoinMarketCap and CoinGecko listings for Web3 projects globally.',
    7
  ),
  (
    'influencer-marketing',
    'Influencer Marketing Services',
    'influencer-marketing-services',
    'Crypto influencer and KOL marketing campaigns — Twitter/X, YouTube, Telegram promotions with vetted creators and measurable engagement results.',
    'Influencer Marketing Services connect your project with verified crypto influencers and Key Opinion Leaders (KOLs) across Twitter/X, YouTube, Telegram, and TikTok. We design, execute, and report on campaigns that drive real awareness, community growth, and holder acquisition.',
    'quote',
    NULL::decimal,
    NULL::decimal,
    'percentage',
    12::decimal,
    '5–10 Days',
    '100% Advance',
    false,
    NULL,
    'hot',
    NULL,
    '["KOL & influencer sourcing","Campaign strategy & creative brief","Multi-platform promotion execution","Twitter/X thread & space campaigns","YouTube review & AMA coordination","Performance & engagement reporting"]',
    '["Twitter/X","YouTube","Telegram","TikTok","Discord"]',
    '[{"title":"Strategy","description":"Define target audience, budget, and campaign KPIs."},{"title":"KOL Matching","description":"Select vetted influencers aligned with your niche."},{"title":"Content Creation","description":"Coordinate posts, videos, threads, and AMAs."},{"title":"Campaign Launch","description":"Execute multi-channel promotion simultaneously."},{"title":"Reporting","description":"Deliver engagement metrics and ROI summary."}]',
    'Influencer Campaign',
    'Global',
    'Non-Refundable after campaign launch',
    ARRAY['Project brief & key messages','Logo and visual assets','Token contract address','Landing page or website URL','Campaign budget allocation'],
    '[{"question":"How do you select influencers?","answer":"We work with a vetted network of 500+ crypto KOLs filtered by niche, engagement rate, and audience authenticity."},{"question":"Can I approve influencers before launch?","answer":"Yes. You approve all KOL selections and content before publication."}]',
    'Influencer content does not constitute financial advice. Results vary by project and market conditions. Campaign fees are non-refundable after KOL content is published.',
    'Executed 100+ influencer campaigns reaching 50M+ combined impressions for Web3 projects.',
    8
  ),
  (
    'pr-distribution',
    'Top Crypto Platforms Advertising Services',
    'top-crypto-platforms-advertising-services',
    'Premium advertising across top crypto media platforms — banner ads, sponsored articles, press releases, and featured placements on leading Web3 publications.',
    'Top Crypto Platforms Advertising Services put your project in front of the right audience on established crypto media outlets. From sponsored articles and press releases to banner placements on CoinTelegraph-tier publications, we secure high-visibility advertising that builds credibility and drives traffic.',
    'quote',
    NULL::decimal,
    NULL::decimal,
    'percentage',
    12::decimal,
    '3–7 Days',
    '100% Advance',
    false,
    NULL,
    NULL,
    NULL,
    '["Crypto media press release distribution","Sponsored article placement","Banner & display advertising","CoinTelegraph-tier publication outreach","News wire distribution (100+ outlets)","Campaign performance analytics"]',
    '["CoinTelegraph","Bitcoin.com","NewsBTC","CryptoSlate","AMBCrypto","U.Today"]',
    '[{"title":"Media Planning","description":"Select target publications and ad formats for your budget."},{"title":"Content Creation","description":"Write press release or sponsored article content."},{"title":"Placement","description":"Secure and publish across selected crypto media platforms."},{"title":"Distribution","description":"Syndicate to 100+ crypto news outlets and aggregators."},{"title":"Analytics","description":"Report impressions, clicks, and referral traffic."}]',
    'Media Advertising',
    'Global',
    'Non-Refundable after content submission to media',
    ARRAY['Press release content or brief','Project logo & images','Official spokesperson quote','Website and social links','Advertising budget confirmation'],
    '[{"question":"Which publications do you advertise on?","answer":"CoinTelegraph, Bitcoin.com, NewsBTC, CryptoSlate, AMBCrypto, U.Today, and 50+ additional crypto media outlets."},{"question":"Do you write the press release?","answer":"Yes. Professional crypto PR writing is included in all advertising packages."}]',
    'Media placement availability varies. We provide outreach and placement services on a best-effort basis. Publication decisions rest with third-party media partners.',
    'Distributed 300+ press releases and ad campaigns across top-tier crypto media with measurable traffic results.',
    9
  )
) AS v(
  cat_slug,
  name,
  slug,
  description,
  overview,
  pricing_model,
  price,
  service_fee,
  commission_type,
  commission_value,
  estimated_tat,
  payment_terms,
  requires_third_party_ack,
  third_party_fee_note,
  badge,
  logo_url,
  whats_included,
  supported_platforms,
  process_steps,
  listing_type,
  networks,
  refund_policy,
  required_documents,
  faqs,
  terms_conditions,
  proof_of_work,
  sort_order
)
JOIN service_categories c ON c.slug = v.cat_slug;
